baseurl:
title: Rupesh K Srivastava
subtitle: Senior Research Scientist
author: Rupesh K Srivastava
simple_search: http://google.com/search
description: Homepage of Rupesh K Srivastava, researcher in Artificial Intelligence
name: rupesh
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/Los_Angeles
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master